### ISSUE TITLE
Increase code readability with line breaks

### ISSUE THREAD

**Issue by sen1** [jeganpillai/intro-data-capstone-biodiversity#1]
https://github.com/jeganpillai/intro-data-capstone-biodiversity/blob/5ecbc0d0a173bd1eb1bd0905a6981da92a133e65/capstone_01/capstone_biodiverse_dataprep.py#L21

A minor comment. I would put a line break to increase code readability. I saw you did that earlier in other places in the code. 
```
category_pivot['percent_protected'] = category_pivot.protected / \
                                      (category_pivot.protected + category_pivot.not_protected)
```

**Comment by jeganpillai** [comment]
Thanks, Since its a formula, I thought of using it in single line :)
