### ISSUE TITLE
Do you know inlining

### ISSUE THREAD

**Issue by sen1** [jeganpillai/intro-data-capstone-biodiversity#2]
https://github.com/jeganpillai/intro-data-capstone-biodiversity/blob/5ecbc0d0a173bd1eb1bd0905a6981da92a133e65/capstone_01/capstone_Nationalpark_service_dataprep.py#L26

Very good job on the plotting. Just want to mention that if you used jupyter, you can use inlining. That will allow you to show a plot without plt.show(). See some examples here at 
http://jakevdp.github.io/mpl_tutorial/tutorial_pages/tut1.html

**Comment by jeganpillai** [comment]
yes I know the inline option. Since I tried in codecademy page, I haven't used it. But I make sure I use it when I try next time. Thanks for the comment
