### ISSUE TITLE
Use of underscore

### ISSUE THREAD

**Issue by sen1** [jeganpillai/intro-data-capstone-biodiversity#3]
https://github.com/jeganpillai/intro-data-capstone-biodiversity/blob/5ecbc0d0a173bd1eb1bd0905a6981da92a133e65/capstone_01/capstone_biodiverse_chitest.py#L9

Good job here as well. An alternate method is:
```
_, pval, _ = chi2_contingency(contingency)
```
Underscore is very special character in python. Explore more at:
https://hackernoon.com/understanding-the-underscore-of-python-309d1a029edc

**Comment by jeganpillai** [comment]
thanks for the tips.
